[versions]
kotlin = "2.3.0"
composeMultiplatform = "1.10.0"
material3 = "1.10.0-alpha05"
kotlinx-coroutines = "1.10.2"
koin = "4.1.1"
pdfbox = "3.0.5"
sqlite-jdbc = "3.50.3.0"
junit = "4.13.2"
jsign = "7.1"

[libraries]
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
jsign-core = { module = "net.jsign:jsign-core", version.ref = "jsign" }

[plugins]
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
